---
# tasks file for vcd_edge_gateway

- name: create edge gateway
  vcd_vdc_gateway:
    gateway_name: edge_gatway
    external_networks:
      - external_network
    state: present
  register: output

- name: create edge gateway output
  debug:
    msg: '{{ output }}'